### PR TITLE
WIP: fix: match classes like `content-`

### PR DESCRIPTION
**Pull request by tmkx**
act like windicss CLI.

---

test.html
```html
<div class="after:content-"></div>
```

generated by `pnpm windicss test.html --output windi.css`
```css
.after\:content-::after {
  content: "";
}
```

---

BTW, maybe it's more pretty to write a `after:content` class to generate empty pseudo element content? 🤔

### CODE REVIEW

**Comment by hannoeru** [comment]
https://github.com/windicss/windicss/blob/bcd50d877e62630f191602ddeabd9f677cc6d90c/src/lib/utilities/dynamic.ts#L1503

PR welcome😉

**Comment by tmkx** [comment]
I have tested in [Tailwind Playground](https://play.tailwindcss.com/QRcB3UU8ms), it uses `after:contents` to create:
```css
.after\:contents::after {
    content: "";
    display: contents;
}
```

`content: ""` will be created only when `before:`/`after:` variant exists.

**Comment by tmkx** [comment]
I had a glance at windicss repo, but I haven't got an idea how to handle `contents` ONLY `before:` / `after:` exists, because that `contents` is defined in `static`.
Maybe I'll take time into it on weekend, if you know how to solve it, just @ me, please.

**Comment by tmkx** [comment]
resolved, close

**Pull request closed without merging**
